### ISSUE TITLE
big_modlist_edit.csv

### ISSUE THREAD

**Issue by rubenwardy** [mdoege/MT-GitSync#1]
You've checked responses to a thread as well, so you have mistakes like this: https://github.com/mdoege/MT-GitSync/blob/master/big_modlist_edit.csv#L14

And you also have links github.com pages which aren't repos:
https://github.com/mdoege/MT-GitSync/blob/master/big_modlist_edit.csv#L119

--------------------------

The csv form is a bit werid as well, it would be better like this:

    modname, title*, git link or http or username/repo, forum topic link
    * no [version] as it may not match the version in the git repo.

It would be useful for finding a mod from its folder (if the user did not download using git).

I'd also like this for https://github.com/rubenwardy/mtpm

I suggest

**Comment by mdoege** [comment]
The initial forum crawling was made by dgm5555 (see forum thread), and yes, there are still some mistakes. The rationale for looking in thread responses was that sometimes people post updated/forked mods in replies.

So you would basically like to add a column for folder names? OK, I'll look into that.

**Comment by rubenwardy** [comment]
Iirc, Krock's mod search indexes downloads, that might be a better choice for me - it's not just git. It's useful to have a list of git repos, though.

Also: homedecor links to xdecor, but not home decor at all. Which is weird.
