### ISSUE TITLE
Wrong entry in big_modlist_edit.csv

### ISSUE THREAD

**Issue by bell07** [mdoege/MT-GitSync#3]
Please check why this entry happens that is not correct:

`Mod Releases • Re: [Mod] Mobs Redo [1.31] [mobs],bell07/minetest-qa_block,https://forum.minetest.net/viewtopic.php?t=9917&p=236813#p236813`

**Comment by Izzyb1234** [comment]
Thanks bell07 - I've deleted it.

**Comment by bell07** [comment]
There are more wrong lines like the both lines among the reported:

> WIP Mods • Re: [Mod] Advanced Trains [advtrains] [1.0.3],alrusdi/blender-b3d-exporter,https://forum.minetest.net/viewtopic.php?t=14726&p=236878#p236878
> WIP Mods • Re: [Mod] Advanced Trains [advtrains] [1.0.3],minetest/B3DExport,https://forum.minetest.net/viewtopic.php?t=14726&p=236896#p236896

Maybe it is not a good idea to apply all posted URL's to the list. Or just as idea, the technical mod name should be contained in github-url. In this case the [advtrains] allow only URL's like "anyuser/advtrains" or "otheruser/minetest-advtrains_new" to be applied
